logging:
  level:
    org.springframework.data.mongodb.core: DEBUG

spring:
  application:
    name: ai-controller
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:17017/JellyStudy?authSource=admin
  ai:
    dashscope:
      api-key: sk-4cfdb9dbbc8c47c48a47b93d43bc5dc6

dubbo:
  application:
    name: dubbo-ai-controller
    qos-enable: false
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20883 
  consumer:
    check: false
    timeout: 10000
    retries: 0

server:
  port: 8085 