logging:
  level:
    org.springframework.data.mongodb.core: DEBUG

spring:
  application:
    name: ai-controller
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:17017/JellyStudy?authSource=admin
  ai:
    dashscope:
      api-key: sk-4cfdb9dbbc8c47c48a47b93d43bc5dc6

dubbo:
  application:
    name: dubbo-ai-controller
    qos-enable: false
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20884
  consumer:
    check: false
    timeout: 3000

server:
  port: 8085

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false
  packages-to-scan: org.example.aicontroller.controller